### ISSUE TITLE
关于IImageMessage和IChatMessage的问题

### ISSUE THREAD

**Issue by GardenHamster** [Executor-Cheng/Mirai-CSharp#109]
![image](https://user-images.githubusercontent.com/89188316/148186865-b1c55118-bb66-425c-8ac4-50e44acd394f.png)

**Comment by GardenHamster** [comment]
版本2.1.2
Mirai.CSharp.HttpApi.Models.ChatMessages包下面是否也可以有一个IImageMessage并且继承IChatMessage

**Comment by Executor-Cheng** [comment]
抱歉3天后我才看到你开的这些issues, 邮箱没提醒我收到新邮件了
一般情况下我会建议你使用 `IMiraiSession.GetMessageChainBuilder` 方法获取到的 `IMessageChainBuilder` 来构建消息链
由于 `Task<T>` 的类型参数非协变, 因此 `MiraiHttpSession` 在覆写基类 `MiraiSession` 的 `UploadPictureAsync` 方法时无法修改其返回类型
不过可以确保的一点是, 从 `MiraiHttpSession.UploadPictureAsync` 返回的 `IImageMessage` 一定实现了 `Mirai.CSharp.HttpApi.Models.ChatMessages.IChatMessage` 接口, 你只需要执行一次强制转换即可

**Comment by GardenHamster** [comment]
谢谢
