### ISSUE TITLE
包含AtMessage消息发送失败

### ISSUE THREAD

**Issue by GardenHamster** [Executor-Cheng/Mirai-CSharp#110]
`await session.SendGroupMessageAsync(args.Sender.Group.Id, new AtMessage(memberId), new PlainMessage("Hello World!"));`

```
调用http-api失败, 参数错误, 请到 https://github.com/Executor-Cheng/Mirai-CSharp/issues 下提交issue。

   在 Mirai.CSharp.HttpApi.Extensions.ApiResponseExtensions.EnsureApiRespCode(JsonElement root)
   在 Mirai.CSharp.HttpApi.Session.MiraiHttpSession.<CommonSendMessageAsync>d__93.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Theresa3rd_Bot.Event.GroupMessageEvent.<HandleMessageAsync>d__0.MoveNext() 在 D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Event\GroupMessageEvent.cs 中: 第 49 行
```

在使用new AtMessage(args.Sender.Id, "")的情况下能发出消息

args.Sender.Id非0

mcl版本1.2.2

Mirai-CSharp版本2.1.2

![image](https://user-images.githubusercontent.com/89188316/149263240-467f8454-cd73-429f-9e1c-1474bb877ed9.png)

**Comment by Executor-Cheng** [comment]
麻烦检查一下你给定的 `memberId` 参数是否有非0值

**Comment by GardenHamster** [comment]
memberId确实不为0，使用IMessageChainBuilder.AddAtMessage也会有同样的问题

**Comment by Executor-Cheng** [comment]
那再检查下这个 `memberId` 是否确实在给定的群号里边

**Comment by GardenHamster** [comment]
![QQ截图20220113234502](https://user-images.githubusercontent.com/89188316/149362574-bab46dda-41b2-42ef-bbef-7d5c19c1295e.png)
![QQ截图20220113234557](https://user-images.githubusercontent.com/89188316/149362595-4c062f86-938f-477d-b820-d38bf2804393.png)
![QQ截图20220113234709](https://user-images.githubusercontent.com/89188316/149362600-2d28ee52-9edd-44bd-ba3f-3e52a7205630.png)

**Comment by GardenHamster** [comment]
构造函数AtMessage(long target, string display)是可以发出来带@的消息的不会报错，但是换成AtMessage(long target)以后就会出问题了
```csharp
IChatMessage[] chain = new IChatMessage[] {
                new AtMessage(args.Sender.Id,""),
                new PlainMessage("emmmm")
            };
await session.SendGroupMessageAsync(args.Sender.Group.Id, chain);
```

**Comment by GardenHamster** [comment]
大佬是没法复现问题吗

**Comment by Executor-Cheng** [comment]
问题已定位, 确实是序列化请求负载的时候错误地添加了 `"display": null` 进去
错误的请求负载: `{"type":"At","target":123,"display":null}`
正确的请求负载: `{"type":"At","target":123}`
非常感谢反馈

**Comment by GardenHamster** [comment]
感谢大佬的工作，期待新版本的发布

**Comment by Executor-Cheng** [comment]
已在 Executor-Cheng/Mirai-CSharp@9f35ced 中完成修复
