### ISSUE TITLE
请问2.X版本他人进退群的事件如何实现

### ISSUE THREAD

**Issue by Alex1911-Jiang** [Executor-Cheng/Mirai-CSharp#111]
1.X版本在session下的 GroupMemberJoinedEvt、GroupMemberPositiveLeaveEvt、GroupMemberKickedEvt 等事件在2.X版本没有了，请问如何实现，可以给个例子吗？谢谢

**Comment by Executor-Cheng** [comment]
首先找到1.X版本中这些事件在2.X下对应的消息模型接口: `IGroupMemberJoinedEventArgs`, `IGroupMemberPositiveLeaveEventArgs`, `IGroupMemberKickedEventArgs`
它们可位于 `Mirai.CSharp.Models.EventArgs`, `Mirai.CSharp.HttpApi.Models.EventArgs` 这两个命名空间之下
前一个是通用抽象, 即不限于 `mirai-api-http`, `mirai-native` 之类的项目
后一个是仅对 `mirai-api-http` 项目下的消息模型抽象
接下来创建你自己的 `Handler`, 它们需要实现这些接口之一:
1. `IContravarianceMiraiMessageHandler<in TClient, in TMessage>`。此接口一般处理项目无关的 `TMessage`。你可以用它处理来自任意不限于 `mirai-api-http`, `mirai-native` 项目的消息。此处给定的 `TMessage` 应位于 `Mirai.CSharp.Models.EventArgs` 下, `TClient` 应为 `IMiraiSession`
2. `IContravarianceMiraiHttpMessageHandler<in TMessage>`。此接口仅处理 `mirai-api-http` 项目发来的消息。也可处理任意比 `TMessage` 派生程度更高的消息
3. `IDedicateMiraiHttpMessageHandler<TMessage>`。此接口仅处理 `mirai-api-http` 项目发来的消息。**仅处理** `TMessage` 类型的消息

基于 `mirai-api-http` 特定实现的实例如下, 我建议使用.NET 5.0+进行开发, 否则某些写法将受到运行时限制:
```csharp
using System.Threading.Tasks;
using Mirai.CSharp.HttpApi.Handlers;
using Mirai.CSharp.HttpApi.Models.EventArgs;
using Mirai.CSharp.HttpApi.Session;

namespace Mirai.CSharp.Example
{
    public class MyMessageHandler : IContravarianceMiraiHttpMessageHandler<IGroupMemberJoinedEventArgs>,
                                    IContravarianceMiraiHttpMessageHandler<IGroupMemberPositiveLeaveEventArgs>,
                                    IContravarianceMiraiHttpMessageHandler<IGroupMemberKickedEventArgs>
    {
        public Task HandleMessageAsync(IMiraiHttpSession client, IGroupMemberJoinedEventArgs message)
        {
            return Task.CompletedTask;
        }

        public Task HandleMessageAsync(IMiraiHttpSession client, IGroupMemberPositiveLeaveEventArgs message)
        {
            return Task.CompletedTask;
        }

        public Task HandleMessageAsync(IMiraiHttpSession client, IGroupMemberKickedEventArgs message)
        {
            return Task.CompletedTask;
        }
    }
}
```
最后使用 `IServiceCollection.AddDefaultMiraiHttpFramework().AddHandler<MyMessageHandler>()` 中完成注册

基于通用模型实现如下:
```csharp
using System.Threading.Tasks;
using Mirai.CSharp.Handlers;
using Mirai.CSharp.Models.EventArgs;
using Mirai.CSharp.Session;

namespace Mirai.CSharp.Example
{
    public class MyMessageHandler : IContravarianceMiraiMessageHandler<IMiraiSession, IGroupMemberJoinedEventArgs>,
                                    IContravarianceMiraiMessageHandler<IMiraiSession, IGroupMemberPositiveLeaveEventArgs>,
                                    IContravarianceMiraiMessageHandler<IMiraiSession, IGroupMemberKickedEventArgs>
    {
        public Task HandleMessageAsync(IMiraiSession client, IGroupMemberJoinedEventArgs message)
        {
            throw new System.NotImplementedException();
        }

        public Task HandleMessageAsync(IMiraiSession client, IGroupMemberPositiveLeaveEventArgs message)
        {
            throw new System.NotImplementedException();
        }

        public Task HandleMessageAsync(IMiraiSession client, IGroupMemberKickedEventArgs message)
        {
            throw new System.NotImplementedException();
        }
    }
}
```
最后使用 `IServiceCollection.AddMiraiBaseFramework().AddHandler<MyMessageHandler>()` 中完成注册

**Comment by Alex1911-Jiang** [comment]
感谢大佬耐心指导, 但我没看明白IContravarianceMiraiHttpMessageHandler和IMiraiHttpMessageHandler之间的关系, session是不是只能添加IMiraiHttpMessageHandler?

**Comment by Executor-Cheng** [comment]
添加 `IMiraiHttpMessageHandler` 是不正确的做法, 这个只是我让编译器去限制加进去的 `THandler` 只能是 `IContravarianceMiraiHttpMessageHandler<in TMessage>` 和 `IDedicateMiraiHttpMessageHandler<TMessage>` 的其中一种

**Comment by Executor-Cheng** [comment]
不过按照框架的玩法, 其实加进去的 THandler 可以比 `IContravarianceMiraiHttpMessageHandler<in TMessage>` 和 `IDedicateMiraiHttpMessageHandler<TMessage>` 的派生程度小, 只是我暂时不清楚怎么样让编译器去确保 `Handler` 正确有效

**Comment by Alex1911-Jiang** [comment]
作用上明白了, 但是原理上似懂非懂, IContravarianceMiraiHttpMessageHandler和IMiraiHttpMessageHandler跟IMiraiHttpMessageHandler没有继承关系, 是怎么约束它只能是IContravarianceMiraiHttpMessageHandler和IDedicateMiraiHttpMessageHandler的一种的呢, 我直接用再上一层的IMiraiHttpMessageHandlerBase是不是也能达到相同的效果并且派生度更小呢?

**Comment by Executor-Cheng** [comment]
啊抱歉, `IMiraiHttpMessageHandler` 和 `IDedicateMiraiHttpMessageHandler` 才是用户端应当实现的接口
我改改上边那一大串代码

**Comment by Alex1911-Jiang** [comment]
怎么感觉又绕回来了, 是不是自己保证Handler正确的时候可以直接无脑用IMiraiHttpMessageHandler, 那什么情况下该用IContravarianceMiraiHttpMessageHandler呢, 或者说Handler"不正确"的情况是什么样的?

**Comment by Executor-Cheng** [comment]
`IContravarianceMiraiHttpMessageHandler` 和 `IInvarianceMiraiHttpMessageHandler` 都不应该由用户侧使用, 它们都被 `IMiraiHttpMessageHandler` 和 `IDedicateMiraiHttpMessageHandler` 分别实现了
只是为了保持框架完整性才去定义的这两个接口

**Comment by Alex1911-Jiang** [comment]
懂了, 谢谢大佬
