### ISSUE TITLE
区分红包和纯文本

### ISSUE THREAD

**Issue by 515621078** [Executor-Cheng/Mirai-CSharp#118]
红包消息为纯文本，“[QQ红包]请使用新版手机QQ查收红包。” 和红包区别不开。
希望能有个区分的功能 谢谢♪(･ω･)ﾉ

**Comment by Executor-Cheng** [comment]
OvO, 由于 mirai 方不打算支持解析红包消息类型, 现有的红包消息均按照 `PlainMessage` 进行传递
参考 mamoe/mirai#1014

**Comment by 515621078** [comment]
并不是要解析红包，在mirai方能告知红包消息是无法解析的，但纯文本和红包消息区别为：
“[QQ红包]请使用新版手机QQ查收红包。”
“[QQ红包]请使用新版手机QQ查收红包。[不支持的消息#- 000000000]”
，用于区分普通文本和红包。
只是想要区分红包和纯文本，至于领取人什么的不需要，这个也不行嘛？

**Comment by Executor-Cheng** [comment]
不行, 只能通过文本这种不可靠的方式来鉴别是否为红包
用于传递红包的消息类型有且只有文本, 所以没办法

**Comment by Executor-Cheng** [comment]
我刚刚自己发了个群红包, `mirai-api-http` 返回了以下的json:
```json
{
	"type": "GroupMessage",
	"messageChain": [{
		"type": "Source",
		"id": 759,
		"time": 1643890209
	}, {
		"type": "Plain",
		"text": "[QQ红包]请使用新版手机QQ查收红包。"
	}],
	"sender": {
		"id": 0,
		"memberName": "西井丶",
		"specialTitle": "",
		"permission": "ADMINISTRATOR",
		"joinTimestamp": 1509110011,
		"lastSpeakTimestamp": 1643890209,
		"muteTimeRemaining": 0,
		"group": {
			"id": 0,
			"name": "For test",
			"permission": "OWNER"
		}
	}
}
```
所以答案很明显了, 就只有这么一点点信息能够拿来判断了
