### ISSUE TITLE
mirai-http已支持商店标签,公告相关接口

### ISSUE THREAD

**Issue by MonsterZhangChen** [Executor-Cheng/Mirai-CSharp#120]
https://github.com/project-mirai/mirai-api-http/releases，
请同步更新一下吧

**Comment by Executor-Cheng** [comment]
好

**Comment by MonsterZhangChen** [comment]
哥，如果能支持一下Mirai code的消息类型就更棒了！现在发消息要传分段数组，很影响开发效率T_T

**Comment by Executor-Cheng** [comment]
已在 Executor-Cheng/Mirai-CSharp@a3346e1 中实现
