### ISSUE TITLE
MiraiHttpSessionOptions 如何使用

### ISSUE THREAD

**Issue by Bunnui** [Executor-Cheng/Mirai-CSharp#122]
serviceCollection.AddOptions<MiraiHttpSessionOptions>（）  为何还传入IServiceCollection？该函数不该是添加MiraiHttpSessionOptions的吗，不是很懂，既然MiraiHttpSessionOptions存在，那他该使用什么函数传进去。

目前还是使用例子中的方法传递
serviceCollection.Configure<MiraiHttpSessionOptions>(options =>
 {
                options.Host = host;
                options.Port = port;
                options.AuthKey = authKey;
 });

![2](https://user-images.githubusercontent.com/37466008/155646225-a171df38-9665-469a-bb65-0e3c0a3346a5.png)

**Comment by Executor-Cheng** [comment]
[Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions<TOptions>(this IServiceCollection)](https://source.dot.net/#Microsoft.Extensions.Options/OptionsServiceCollectionExtensions.cs,0d90cd2ff970fa74)
什么是[扩展方法](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/classes-and-structs/extension-methods)？

**Comment by Executor-Cheng** [comment]
首先你需要了解什么叫[依赖注入(DI)](https://docs.microsoft.com/zh-cn/dotnet/core/extensions/dependency-injection)
默认情况下, `MiraiHttpSessionOptions` 将作为 `IOptions<MiraiHttpSessionOptions>`, 生命周期为单例(Singleton)在容器中注册
想要获取该实例, 只需要在构造函数签名中加上 `IOptions<MiraiHttpSessionOptions>` 参数即可获取实例, 或者用 `IServiceProvider.Get(Required)Service<T>` 方法从容器中获取
```csharp
serviceCollection.Configure(options =>
{
    options.Host = host;
    options.Port = port;
    options.AuthKey = authKey;
});
```
这段代码实际上是调用了 [Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.Configure<TOptions>(this IServiceCollection, Action<TOptions>)](https://source.dot.net/#Microsoft.Extensions.Options/OptionsServiceCollectionExtensions.cs,b5db69a84107f087) 对 `MiraiHttpSessionOptions` 进行初始化, 你也可以用另外的扩展方法将其绑定到 `IConfiguration` 里
如有疑问欢迎继续提问(°∀°)ﾉ
