### ISSUE TITLE
请教一下关于Linux系统缺库的问题

### ISSUE THREAD

**Issue by Alex1911-Jiang** [Executor-Cheng/Mirai-CSharp#123]
大佬你帮我添加依赖引用之后我重新以linux-64平台发布依旧报找不到 libsilklame , 是我发布的方式不对吗, 我看你改的是BotMain的库, 但我发布的是Console, BotMain需要单独发布成nupkg吗?

**Comment by Executor-Cheng** [comment]
我在`GreenOnions\bin\release\net5.0\publish\linux-x64`目录下能看到`libsilklame.so`和`libSkiaSharp.so`这两个依赖诶
你试试清除解决方案然后重新发布一次

**Comment by Alex1911-Jiang** [comment]
哦哦可以了, 谢谢大佬
