### ISSUE TITLE
如何接收并回复群临时消息

### ISSUE THREAD

**Issue by GardenHamster** [Executor-Cheng/Mirai-CSharp#125]
尝试了使用ITempMessageEventArgs接收消息，但是在没有添加bot为好友的情况下通过群给bot发消息，没有任何触发
```csharp
[RegisterMiraiHttpParser(typeof(DefaultMappableMiraiHttpMessageParser<ITempMessageEventArgs, TempMessageEventArgs>))]
    public class TempMessageEvent : IMiraiHttpMessageHandler<ITempMessageEventArgs>
    {
        public async Task HandleMessageAsync(IMiraiHttpSession session, ITempMessageEventArgs args)
        {
            
        }
```

**Comment by Executor-Cheng** [comment]
![p1](https://user-images.githubusercontent.com/27953325/159243983-5fd1208c-83bc-4a9c-8801-047111528e14.png)
我没能复现问题
你是怎么注册这个 `TempMessageEvent` 的能贴一下不

**Comment by Executor-Cheng** [comment]
https://github.com/Executor-Cheng/Mirai-CSharp/blob/430f2f482233a5e146454de73bb45133e43f4a88/Mirai-CSharp.HttpApi/Session/MiraiHttpSession.ReceiveMessage.cs#L55
那只有两种可能了, 1是连接断开没有重连, 2是本框架没收到mah发来的消息
辛苦clone一次本项目, 然后在你的项目中直接引用本项目, 在以下地方置一个断点:
https://github.com/Executor-Cheng/Mirai-CSharp/blob/430f2f482233a5e146454de73bb45133e43f4a88/Mirai-CSharp.HttpApi/Session/MiraiHttpSession.ReceiveMessage.cs#L55
然后你再发一次临时消息, 看看断点是否命中, 且 `root.GetProperty("type").GetString()` 应为 `TempMessage`

**Comment by GardenHamster** [comment]
好的，辛苦大佬了

**Comment by GardenHamster** [comment]
问题找到了，是因为bot没有设置接收临时会话

**Comment by GardenHamster** [comment]
顺便请问下大佬要怎么回复接收到的临时消息

**Comment by Executor-Cheng** [comment]
使用 `IMiraiSession.SendTempMessageAsync` 方法即可

**Comment by GardenHamster** [comment]
> 使用 `IMiraiSession.SendTempMessageAsync` 方法即可

尝试用了一下,但是消息并没有发出来

**Comment by Executor-Cheng** [comment]
你之前开了个 #113 
看一看是不是相同的问题?

**Comment by GardenHamster** [comment]
需求不一样了，以前是主动发私聊，现在是想回复私聊

**Comment by Executor-Cheng** [comment]
https://github.com/Executor-Cheng/Mirai-CSharp/blob/430f2f482233a5e146454de73bb45133e43f4a88/Mirai-CSharp/Session/MiraiSession.SendMessage.cs#L63
https://github.com/Executor-Cheng/Mirai-CSharp/blob/430f2f482233a5e146454de73bb45133e43f4a88/Mirai-CSharp/Session/MiraiSession.SendMessage.cs#L69
https://github.com/Executor-Cheng/Mirai-CSharp/blob/430f2f482233a5e146454de73bb45133e43f4a88/Mirai-CSharp/Session/MiraiSession.SendMessage.cs#L78
抱歉抱歉, 我在写基类的时候参数给错了, 这就发一版preview解决这个问题

**Comment by GardenHamster** [comment]
谢谢，辛苦大佬了
