### ISSUE TITLE
添加对cq-http的支持

### ISSUE THREAD

**Issue by baka-gourd** [Executor-Cheng/Mirai-CSharp#127]
现在的mirai有点一言难尽，是否可添加对cq-http的支持
https://github.com/Mrs4s/MiraiGo
https://github.com/Mrs4s/go-cqhttp

**Comment by Executor-Cheng** [comment]
`mirai` 与 `MiraiGo` 是两个框架, 所以实现 `MiraiGo` 不应放在本repo下
等我忙完毕业的必要事情后可以考虑写一下
