### ISSUE TITLE
哪个，您好······我想请教 一个问题，关于linux发布的问题

### ISSUE THREAD

**Issue by You-Bass** [Executor-Cheng/Mirai-CSharp#129]
我看到了您对其他成员的答复
我可能也问同样的问题
如有打扰我感到抱歉
报错： Unable to load shared library 'libsilklame' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibsilklame: cannot open shared object file: No such file or directory
系统是Ubuntu 20.04LTS

**Comment by You-Bass** [comment]
谢谢你呐，我编译了您的仓库silklame，现在已经有libsilklame了，现在去试试

**Comment by You-Bass** [comment]
Unhandled exception. System.ArgumentException: 调用http-api失败, 参数错误, 请到 https://github.com/Executor-Cheng/Mirai-CSharp/issues 下提交issue。
   at Mirai.CSharp.HttpApi.Extensions.ApiResponseExtensions.EnsureApiRespCode(JsonElement root)
   at Mirai.CSharp.HttpApi.Session.MiraiHttpSession.CommonSendMessageAsync(String action, Nullable`1 qqNumber, Nullable`1 groupNumber, IChatMessage[] chain, Nullable`1 quoteMsgId, CancellationToken token)
   at HuobanForDotnet.MyMiraiBot.SendNewQuestion() in C:\Users\together\source\repos\HuobanForDotnet\HuobanForDotnet\MyMiraiBot.cs:line 83
   at HuobanForDotnet.MyMiraiBot.SendNewQuestion() in C:\Users\together\source\repos\HuobanForDotnet\HuobanForDotnet\MyMiraiBot.cs:line 89
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by You-Bass** [comment]
呜哇，抱歉·······我又来了······

**Comment by Executor-Cheng** [comment]
辛苦提供一下 `MyMiraiBot.cs` 第83行的代码

**Comment by You-Bass** [comment]
嗯，哪个，由于代码的改动，报错信息已变更
Unhandled exception. System.AggregateException: One or more errors occurred. (调用http-api失败, 参数错误, 请到 https://github.com/Executor-Cheng/Mirai-CSharp/issues 下提交issue。)
 ---> System.ArgumentException: 调用http-api失败, 参数错误, 请到 https://github.com/Executor-Cheng/Mirai-CSharp/issues  下提交issue。
   at Mirai.CSharp.HttpApi.Extensions.ApiResponseExtensions.EnsureApiRespCode(JsonElement root)
   at Mirai.CSharp.HttpApi.Session.MiraiHttpSession.CommonSendMessageAsync(String action, Nullable`1 qqNumber, Nullable`1 groupNumber, IChatMessage[] chain, Nullable`1 quoteMsgId, CancellationToken token)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConnectBot.Program.Main(String[] args) in C:\Users\together\source\repos\ConnectBot\ConnectBot\Program.cs:line 65
在这其中，ConnectBot.Program.Main的第65行代码为
session.SendFriendMessageAsync(2938752629, chain).Wait();//异步方法，发送信息
因为这个发送消息的方法会放在System.Timers声明的Timer中，所以方法的返回值不能为Task，所以不能加“await”

**Comment by You-Bass** [comment]
整个ConnectBot.Program.cs的文件是这个样子的
using Microsoft.Extensions.DependencyInjection;
using Mirai.CSharp.Builders;
using Mirai.CSharp.HttpApi.Builder;
using Mirai.CSharp.HttpApi.Handlers;
using Mirai.CSharp.HttpApi.Invoking;
using Mirai.CSharp.HttpApi.Models.ChatMessages;
using Mirai.CSharp.HttpApi.Models.EventArgs;
using Mirai.CSharp.HttpApi.Options;
using Mirai.CSharp.HttpApi.Parsers;
using Mirai.CSharp.HttpApi.Parsers.Attributes;
using Mirai.CSharp.HttpApi.Session;
using System;
using System.Threading.Tasks;

namespace ConnectBot
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // 一套能用的框架, 必须要注册至少一个 Invoker, Parser, Client 和 Handler
            // Invoker 负责消息调度
            // Parser 负责解析消息到具体接口以便调度器调用相关 Handler 下的处理方法
            // Client 负责收发原始数据
            IServiceProvider services = new ServiceCollection().AddMiraiBaseFramework()   // 表示使用基于基础框架的构建器
                                                              .AddHandler<MiraiPlugin>() // 虽然可以把 HttpApiPlugin 作为泛型参数塞入, 但不建议这么做
                                                              .Services
                                                              .AddDefaultMiraiHttpFramework() // 表示使用 mirai-api-http 实现的构建器
                                                              .ResolveParser<DynamicPlugin>() // 只提前解析 DynamicPlugin 将要用到的消息解析器
                                                              .AddInvoker<MiraiHttpMessageHandlerInvoker>() // 使用默认的调度器
                                                              .AddHandler<HttpApiPlugin>() // 可以如此添加更多消息处理器
                                                              .AddClient<MiraiHttpSession>() // 使用默认的客户端
                                                              .Services
                                                              // 由于 MiraiHttpSession 使用 IOptions<MiraiHttpSessionOptions>, 其作为 Singleton 被注册
                                                              // 配置此项将配置基于此 IServiceProvider 全局的连接配置
                                                              // 如果你想一个作用域一个配置的话
                                                              // 自行做一个实现类, 继承MiraiHttpSession, 构造参数中使用 IOptionsSnapshot<MiraiHttpSessionOptions>
                                                              // 并将其传递给父类的构造参数
                                                              // 然后在每一个作用域中!先!配置好 IOptionsSnapshot<MiraiHttpSessionOptions>, 再尝试获取 IMiraiHttpSession
                                                              .Configure<MiraiHttpSessionOptions>(options =>
                                                              {
                                                                  options.Host = "43.154.27.37";
                                                                  //options.Host = "192.168.1.1";
                                                                  //options.Host = "team.lemonsgame.cn";
                                                                  options.Port = 11414; // 端口
                                                                  options.AuthKey = "youbass20220506"; // 凭据
                                                              })
                                                              .AddLogging()
                                                              .BuildServiceProvider();
            IServiceScope scope = services.CreateScope();
            var x = (IAsyncDisposable)scope;
            //await using AsyncServiceScope scope = services.CreateAsyncScope(); // 自 .NET 6.0 起才可以如此操作代替上边两句
            services = scope.ServiceProvider;
            IMiraiHttpSession session = services.GetRequiredService<IMiraiHttpSession>(); // 大部分服务都基于接口注册, 请使用接口作为类型解析
            DynamicPlugin plugin = new DynamicPlugin();
            PluginResistration resistration = session.AddPlugin(plugin); // 实时添加
            session.ConnectAsync(3571107635).Wait(); // 填入期望连接到的机器人QQ号
            var stateMessage = new PlainMessage("Test");//从stateInfo中拿到第一个信息
            IChatMessage msg = stateMessage;//打包信息类

            IChatMessage[] chain = new IChatMessage[] { msg }; // 数组里边可以加上更多的 IMessageBase, 以此达到例如图文并发的情况
                                                               //await session.SendTempMessageAsync(2938752629, 1009567831, chain);
                                                               //await session.SendGroupMessageAsync(853744936, chain);
            if (session != null)
               session.SendFriendMessageAsync(2938752629, chain).Wait();//异步方法，发送信息
            else
                Console.WriteLine("会话出现了空引用");
        }
        #region 
        [RegisterMiraiHttpParser(typeof(DefaultMappableMiraiHttpMessageParser<IGroupMessageEventArgs, GroupMessageEventArgs>))]
        public class MiraiPlugin : IMiraiHttpMessageHandler<IGroupMessageEventArgs>
        {
            // 使用 .NET Core 时, 删去 override 和 基类继承
            public Task HandleMessageAsync(IMiraiHttpSession session, IGroupMessageEventArgs message)
            {
                return Task.CompletedTask;
            }
        }
        [RegisterMiraiHttpParser(typeof(DefaultMappableMiraiHttpMessageParser<IGroupMessageEventArgs, GroupMessageEventArgs>))]
        public class DynamicPlugin : IMiraiHttpMessageHandler<IGroupMessageEventArgs>
        {
            // 使用 .NET Core 时, 删去 override 和 基类继承
            public Task HandleMessageAsync(IMiraiHttpSession session, IGroupMessageEventArgs message)
            {
                return Task.CompletedTask;
            }
        }
        [RegisterMiraiHttpParser(typeof(DefaultMappableMiraiHttpMessageParser<IGroupMessageEventArgs, GroupMessageEventArgs>))]
        public class HttpApiPlugin : IMiraiHttpMessageHandler<IGroupMessageEventArgs> // .NET Core 起, 你应该直接实现 IMiraiHttpMessageHandler<TMessage> / IDedicateMiraiHttpMessageHandler<TMessage> 接口
        {
            // 使用 .NET Core 时, 删去 override 和 基类继承
            public Task HandleMessageAsync(IMiraiHttpSession session, IGroupMessageEventArgs message)
            {
                return Task.CompletedTask;
            }
        }
        #endregion
    }
}

**Comment by Executor-Cheng** [comment]
查明原因是 `mirai-api-http` v2.5.0 与 `mirai` v2.10.1 不兼容导致的情况
更新 `mirai` 至 v2.11.0+ 即可
