### ISSUE TITLE
GetUserProfileAsync失败（已找到解决办法，麻烦作者修复这个问题）

### ISSUE THREAD

**Issue by q2398003522** [Executor-Cheng/Mirai-CSharp#133]
失败原因是Mirai-CSharp的调用与Mirai-Http-Api的接口不一致，可能是Mirai-Http-Api更新导致的，见[https://docs.mirai.mamoe.net/mirai-api-http/api/API.html#%E8%8E%B7%E5%8F%96qq%E7%94%A8%E6%88%B7%E8%B5%84%E6%96%99](url)
解决办法：
Mirai-CSharp.HttpApi\Session\MiraiHttpSession.FetchProfile.cs
44行 GetAsync第一个参数改为 `$"{_options.BaseUrl}/userProfile?sessionKey={session.SessionKey}&target={qqNumber}"`

**Comment by Executor-Cheng** [comment]
感谢反馈~~
测试后没有问题，也欢迎提PR嗷
