### ISSUE TITLE
2.1.9计划

### ISSUE THREAD

**Issue by Executor-Cheng** [Executor-Cheng/Mirai-CSharp#137]
感谢 @Cyl18 的[批评和意见](https://github.com/Cyl18/Chaldene/blob/main/docs/complicate.md)

- [x] 异步等待时使用 `ConfigureAwait(bool)`
- [x] 提供可在 LinuxArm 环境下使用的 NativeAssets: `Mirai-CSharp.NativeAssets.LinuxArm`
- [ ] 再次简化文档
- [x] 允许配置 `MiraiHttpSessionOptions.BaseUrl` 为 https
- [ ] 支持仅使用 `mirai-api-http` 下的 `HttpAdapter` / `WsAdapter`, 或者二者兼用
- [ ] ~~更改 `Mirai-CSharp`基础项目下的命名, 在其后全部添加 `Base` 以便区分基于基础框架还是基于实现框架 (由于是破坏性更改,暂时延迟)~~

**Comment by Cyl18** [comment]
不好意思没有反馈这些问题而是在那里闷着说

关于https的问题  
![image](https://user-images.githubusercontent.com/14993992/189512746-9941ac99-a74f-4dc5-a25b-357a938b164e.png)  
我以为我给 Mirai-CSharp 发了，但是没有...大概是因为我觉得TA们的态度都不太欢迎 https, 就没给你发了，主要是我个人要把 bot 挂在公网有需求

关于native问题
建议弄成可选依赖？

关于 ConfigureAwait  
我发过 #51 

关于库太复杂的问题  
我是比较喜欢 Mirai-CSharp v1 式的 API，但是就是现在文档看着有点乱，改改大概也能降低学习成本

关于 HttpAdapter 问题  
这个其实是 mirai-api-http 本身的问题 我自己去 TA 们那边 [发过 issue](https://github.com/project-mirai/mirai-api-http/issues/474), 就是 ws 不能单独用谁都很烦

总之还是非常感谢你能抽时间解决这些问题的❤

**Comment by Executor-Cheng** [comment]
哪里，我才是要感到不好意思的那一个，老鸽子了导致文档一直没能写得很好
native作为可选是个不错的选择
为啥我要v1的api的原因是因为往后再加event会使得一个类下边的成员太多，导致其体积太大，也不易于维护。用到DI也是因为我觉得解耦是很有必要去做的。如果还是按照v1，那在接受消息的时候就势必要根据cmd进行体积超长的`switch`，同样会降低可维护性
`HttpAdapter`这个好说，做个轮询的就行了
晚上泡杯咖啡开工，我感觉我已经亚健康了，动不动就觉得没精神然后就咕了，你也加油呀
