### ISSUE TITLE
示例代码  AddParser 报错

### ISSUE THREAD

**Issue by lhtuling** [Executor-Cheng/Mirai-CSharp#139]
![image](https://user-images.githubusercontent.com/44140500/190915486-7cb51051-fadf-4b3c-9623-974eb9c4e481.png)
大佬给力啊  正好要搞个练练手  查了好多资料偶然间发现这个项目

**Comment by Executor-Cheng** [comment]
在 `AddDefaultMiraiHttpFramework` 后的 `AddParser` 方法中的泛型类型都位于 `Mirai.CSharp.HttpApi.Models.EventArgs` 下
所以稍微修改下你的using就行了

**Comment by lhtuling** [comment]
> 在 `AddDefaultMiraiHttpFramework` 后的 `AddParser` 方法中的泛型类型都位于 `Mirai.CSharp.HttpApi.Models.EventArgs` 下 所以稍微修改下你的using就行了

提示的是不包含这个方法   不是后面的泛型类型问题吧
![image](https://user-images.githubusercontent.com/44140500/190943852-3f1a916d-796c-41c6-8342-35a31933cd5c.png)

**Comment by Executor-Cheng** [comment]
原来如此，那辛苦你装一下 `Mirai-CSharp.HttpApi` 这个nuget包

**Comment by lhtuling** [comment]
> 原来如此，那辛苦你装一下 `Mirai-CSharp.HttpApi` 这个nuget包

装过的  还是报错
![image](https://user-images.githubusercontent.com/44140500/190946139-9b2e3b3d-2593-44c0-90e0-7e934ae26768.png)

**Comment by Executor-Cheng** [comment]
那应该是这么一回事儿，你把 `AddParser` 提前到 `AddInvoker` 上边

**Comment by Executor-Cheng** [comment]
问题解决了嘛？解决了记得关闭一下issue
