### ISSUE TITLE
发送好友消息中一条消息链里同时存在文字和图片，别人收不到

### ISSUE THREAD

**Issue by Alex1911-Jiang** [Executor-Cheng/Mirai-CSharp#141]
大佬好，这个Issue大概是个求助，如题所说，因为消息mirai上都能显示，所以我猜应该不是大佬的问题

Mirai-CSharp 版本 2.1.9-preview.1
mirai core/console/terminal 版本 2.12.1 / 2.13.0
mirai-api-http 版本 2.6.2

群：
![群代码](https://user-images.githubusercontent.com/50268952/202851597-8f539236-1cde-4c73-8cb2-d414bdef728e.jpg)
好友：
![私聊代码](https://user-images.githubusercontent.com/50268952/202851620-32c1a735-21bd-4485-9492-0e1dd9ec6c43.jpg)
mirai显示：
![mirai](https://user-images.githubusercontent.com/50268952/202851674-cda73fce-201e-4b56-96b2-4b7c0456b77d.jpg)
看起来一切正常，群里能正常收到，但是好友就是收不到消息，单独发文字或者单独发图片就都可以收到。

由于不知道是哪的问题所以来求助一下万能的大佬

**Comment by Executor-Cheng** [comment]
![太怪了，再望一眼](https://user-images.githubusercontent.com/27953325/202856113-7db70860-d860-4283-8b99-cff24c9c2d95.png)
我这边好像没有这种问题, mirai 相关组件的版本号是 `2.12.0`, `http-api` 版本是 `2.5.2`
使用的代码如下
```csharp
var builder = session.GetMessageChainBuilder();
builder.AddImageMessage(url: "https://static.dream.day/stickers/usaginono/tglzwyy.jpg");
builder.AddPlainMessage("test");
await session.SendFriendMessageAsync(destination, builder);
```

**Comment by Alex1911-Jiang** [comment]
怪，我试出来了，似乎是tx对地址的过滤，文字内容中含有 ".pixiv." 就会发不出去，但是单独发一条地址不发图的话又可以，太怪了

**Comment by Executor-Cheng** [comment]
那还是先在程序里直接先请求图片, 之后从 `HttpResponseMessage.Content` 通过 `ReadAsStreamAsync` 拉一个 `Stream`, 最后直接调用 `UploadPictureAsync` 上传再发会好一些？

**Comment by Alex1911-Jiang** [comment]
跟图片的URL没有关系，我试过了发本地路径或者MemoryStream的图片都一样，是含有图片的那条消息中的文字部分含有 ".pixiv." 就会整条发不出去。
真实手机端又确实不能图片和文字在一条消息中发，所以我也没法测试真实客户端能不能发出去，pc倒是没问题能整条两个部分都发出去，我到社区问问吧，谢谢大佬耐心解答
