### ISSUE TITLE
使用MemoryStream构建VoiceMessage手机端接收听不了

### ISSUE THREAD

**Issue by Alex1911-Jiang** [Executor-Cheng/Mirai-CSharp#142]
mirai三件套 版本 2.10.1
mirai-api-http 版本 2.4.0
Mirai-CSharp 版本 2.1.9-preview.1

已经 AddSilkLameVoiceConverter()

消息能发出去，好友能收到，时长看起来也是对的，并且电脑端好友可以正常播放，但是手机端点播放没有声音并且半秒就停了
我把MemoryStream保存了下来，电脑可以播，以真实PC客户端把这个文件发给手机端的话手机端也能播。
在PC端登机器人的QQ看发出去的消息会看到一条裂掉的语音。
[炉心融解.zip](https://github.com/Executor-Cheng/Mirai-CSharp/files/10148627/default.zip)

另外，SendFriendMessageAsync发送VoiceMessage，会是收到一条没有QQ号的用户发来的临时消息，而不是正在对话的好友，如果没有开启临时会话，则只能看到QQ图标闪烁一只企鹅，点击后会弹出必须添加好友才能对话的提醒。
群消息没问题。

再顺便问个事，IMiraiHttpSession我看它实现了IDisposable，但是我退出登录的时候调用Dispose()方法会永远卡住无法执行下去，我看您例子没调，所以是不是不用调就行？

**Comment by Alex1911-Jiang** [comment]
不急，大佬慢慢来，顺带一提，以前的版本（拆成单独的包之前）从网上获取的图片MemoryStream，也是直接发的时候会异常，需要我重新new一个MemoryStream并把从网上下的那个ToArray()一下才能发出去（就是网上下的MemoryStream，.GetBuffer()和.ToArray()的结果不一样，可能不是连续的？）音频我也尝试的相同的操作，没有效果

**Comment by Executor-Cheng** [comment]
似乎现阶段 `mirai-api-http` 不支持上传用于发送给好友的语音: [接口文档](https://docs.mirai.mamoe.net/mirai-api-http/adapter/HttpAdapter.html#%E8%AF%AD%E9%9F%B3%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0)
上传给群是正常工作的。不过顺便发现了这里重复了一句的问题
https://github.com/Executor-Cheng/Mirai-CSharp/blob/0127929c658147978856908b1b19899e0fce4432/Mirai-CSharp.HttpApi/Session/MiraiHttpSession.SendVoice.cs#L86

> 不急，大佬慢慢来，顺带一提，以前的版本（拆成单独的包之前）从网上获取的图片MemoryStream，也是直接发的时候会异常，需要我重新new一个MemoryStream并把从网上下的那个ToArray()一下才能发出去（就是网上下的MemoryStream，.GetBuffer()和.ToArray()的结果不一样，可能不是连续的？）音频我也尝试的相同的操作，没有效果

以前的版本是因为我读取完用户提供的 `Stream` 后, 忘了给自己内部的 `MemoryStream` 调用 `Seek(0, SeekOrigin.Begin)`, 导致后续的操作读了个寂寞

**Comment by Alex1911-Jiang** [comment]
不是不是，上传给群也只有电脑端可以听，手机端听不了。
群和好友是两个问题，好友没有api其实问题不大。
还有刚刚发现了，如果我用本地文件路径构造VoiceMessage，情况会反过来，PC客户端显示只有1秒且无法播放，手机端能正常播放。

**Comment by Executor-Cheng** [comment]
> 不是不是，上传给群也只有电脑端可以听，手机端听不了。 群和好友是两个问题，好友没有api其实问题不大。 还有刚刚发现了，如果我用本地文件路径构造VoiceMessage，情况会反过来，PC客户端显示只有1秒且无法播放，手机端能正常播放。

是这样的, 我测了下传群语音, 手机和电脑TIM都能正常播放诶
另外如果使用本地路径构建语音消息实体, 转换操作将由mirai负责

**Comment by Alex1911-Jiang** [comment]
mirai更到了正式最新，IOS还是播放不了，我翻到了一条mirai去年的Issue，似乎是不支持mp3 https://github.com/mamoe/mirai/issues/946 
我尝试一下转成amr格式吧

**Comment by Executor-Cheng** [comment]
> mirai更到了正式最新，IOS还是播放不了，我翻到了一条mirai去年的Issue，似乎是不支持mp3 [mamoe/mirai#946](https://github.com/mamoe/mirai/issues/946) 我尝试一下转成amr格式吧

按理说mp3会被我提供的Converter转为silk的
但我不幸弱阳了, 好转后再来查看一下
