### ISSUE TITLE
关于图片上传产生的临时文件

### ISSUE THREAD

**Issue by GardenHamster** [Executor-Cheng/Mirai-CSharp#145]
在执行Session.UploadPictureAsync方法后
`C:\Users\Administrator\AppData\Local\Temp`或者`C:\Users\Administrator\AppData\Local\Temp\2`目录下会出现类似`file-upload11394565611600402215.tmp`这样的临时文件
在发送图片频率比较高的情况下，会占用C盘比较多的空间，请教一下有api可以清理这些临时文件吗
![image](https://user-images.githubusercontent.com/89188316/212878309-89afc394-6789-47ed-8625-816870d74ded.png)

**Comment by Executor-Cheng** [comment]
这些临时文件均由 mirai 创建, 它可能没有实现正确的删除方法, 你可能需要自己定时清理一下
本项目完全不会向本地磁盘写入任何文件

**Comment by GardenHamster** [comment]
懂了，谢谢佬
