### ISSUE TITLE
请问该框架支持并发处理消息吗

### ISSUE THREAD

**Issue by qinjin2** [Executor-Cheng/Mirai-CSharp#153]
将调度器，处理器等五个生命周期都改为Transient了，但在上一条请求处理完之前，下一条请求都不会被处理

**Comment by Executor-Cheng** [comment]
置 `MiraiHttpSessionOptions.SuppressAwaitMessageInvoker` 为 `true` 即可满足你的要求

**Comment by qinjin2** [comment]
翻之前的issue的时候已经看见了，感谢大佬🙏
