### ISSUE TITLE
如何主动调出session并调用方法

### ISSUE THREAD

**Issue by traceless0929** [Executor-Cheng/Mirai-CSharp#17]
我把mirai-csharp和asp .net core 整合在一起，例如我有个api方法中，想使用调用MiraiHttpSession 发送我指定的内容给指定群，需要如何优雅实现呢？目前只能在事件回调的参数中使用MiraiHttpSession

**Comment by Executor-Cheng** [comment]
目前的设计是一个Session对一个Bot的, 在asp里边你可能得做个Service, 它管理Session的注册销毁, 还有Retrive, 然后每次你获取自己的Service去拿Session就行了

**Comment by traceless0929** [comment]
好的 那就说要自己处理 mirai-csharp并没有提供相关session管理器

**Comment by Executor-Cheng** [comment]
> 好的 那就说要自己处理 mirai-csharp并没有提供相关session管理器

嗯，暂时没考虑到这么多
