### ISSUE TITLE
用Nuget引入的类库疑似缺乏组件

### ISSUE THREAD

**Issue by expectmiu** [Executor-Cheng/Mirai-CSharp#20]
本人使用VS获取了您的Mirai_CSharp类库,发现在实现时无法和例子中一样使用IGroupMessage接口,核对了Github上的代码发现我下载到的类库中不包含Plugin.Interface的整个命名空间,如图所示

![Snipaste_2020-09-12_19-15-06](https://user-images.githubusercontent.com/26505276/92994456-e0f8f680-f52c-11ea-8aa7-fac434aa5747.png)

怀疑是bug,望核查

顺便一提,本人虽用C#工作,但是用这个库还是令我大开眼界,学了很多东西才搞清楚用法(假的IT人,Orz

提前为可能因此而造成的误报抱歉_(: 」∠)_

(目前在考虑直接拿这个git上面的代码用,似乎能复制过来用的样子)

**Comment by Executor-Cheng** [comment]
感谢对本项目的支持和肯定
因为`.NET Standard 2.0`及以下的CLR不支持默认接口实现这一功能, 所以在这个框架下的本项目没有`Mirai-CSharp.Plugin.Interface`这个命名空间。
在csproj里边我专门加了条件排除的句子, 指示当目标框架为`.NET Standard 2.0`时, `Plugin\Interfaces`文件夹下的所有文件均不编译
https://github.com/Executor-Cheng/Mirai-CSharp/blob/365c79f8bb213322e02017501975cf37178ec3de/Mirai-CSharp/Mirai-CSharp.csproj#L38-L42
尝试编译时, 编译器会抛出`CS8701	Target runtime doesn't support default interface implementation.`
所以你需要为你的插件类自行实现`IPlugin<TEventArgs>`接口, 比如你要收群消息就实现`IPlugin<IGroupMessageEventArgs>`接口, 在实现类中定义一个`Task<bool> IPlugin<IGroupMessageEventArgs>.HandleEvent(MiraiHttpSession session, IGroupMessageEventArgs e)`方法

**Comment by expectmiu** [comment]
谢谢Orz
这下才知道.Net Framework和.Net Standard的关系_(: 」∠)_长见识了

**Comment by Executor-Cheng** [comment]
详细的关系看这里: [官方文档](https://docs.microsoft.com/zh-cn/dotnet/standard/net-standard)
一句话就是, .NET Framework没法用, 小于.NET Core 3.0的也没法用
