### ISSUE TITLE
请求添加版本说明

### ISSUE THREAD

**Issue by expectmiu** [Executor-Cheng/Mirai-CSharp#21]
最近Mirai API Http似乎进行了不兼容更新, 不知道这个框架是否是兼容两种版本的, 同时我注意到Nuget上可以下载到多版本的Mirai-CSharp,也许在read me中加个说明会比较好?

即,希望说明Mirai-CSharp和Mirai-API-Http之间版本的关系

(顺便,我也没搞清楚到底是否兼容,至今机器人还没跑起来,还抛类似于"无法识别的指令"的异常,Orz

附:使用的Nuget包为Mirai-CSharp 1.0.2.1

**Comment by Executor-Cheng** [comment]
本项目与`mirai-api-http`的版本无关
没跑起来的话, 你可以Clone本项目, 直接在你自己的项目中进行引用, 然后善用调试器
当然, 有其它的问题也可以开新的Issue来提, 本Issue我先关了

**Comment by expectmiu** [comment]
谢谢!

刚刚在解决自己的程序的bug后发现迷迷糊糊地配置了一种结构发现可以跑,谢谢你勤劳回复!
