### ISSUE TITLE
消息类的一些问题

### ISSUE THREAD

**Issue by Miyakowww** [Executor-Cheng/Mirai-CSharp#24]
https://github.com/Executor-Cheng/Mirai-CSharp/blob/365c79f8bb213322e02017501975cf37178ec3de/Mirai-CSharp/Models/Messages/PlainMessage.cs#L19
建议改为 private set，包括其他地方id、target之类的属性，按理说这些属性在实例化以后不应该被修改

主要是我希望把消息链逐个传到每个模块中处理消息的方法，希望能从语法上避免前面的模块不小心修改了消息的内容导致后面的模块处理出现异常的问题

**Comment by Executor-Cheng** [comment]
非`public set`会影响`.NET 5.0`以下的目标框架进行Json反序列化, `JsonSerializer`要求`public`的`set`访问器
对于`.NET 5.0`的实现, 我可能会用`record`+`init`, 或者干脆就只有`get`访问器
对于其它的`EventArgs`我也有差不多的想法, 毕竟STJ现在已经支持使用特定的`JsonConstructor`了
