### ISSUE TITLE
Linux下发送图片方法UploadPictureAsync失效

### ISSUE THREAD

**Issue by kami-poi** [Executor-Cheng/Mirai-CSharp#25]
在linux系统下，调用UploadPictureAsync将会无限等待发送，无法上传图片。

**Comment by Executor-Cheng** [comment]
麻烦提供一下所用的`Mirai-CSharp`版本、`mirai-api-http`版本
`UploadPictureAsync`在不同的版本/条件下会有不同的`behavior`

**Comment by kami-poi** [comment]
Mirai-CSharp : _1.0.2.1_
mirai-api-http : _1.8.3_
一直没看邮件，抱歉拖了那么久才回

**Comment by Executor-Cheng** [comment]
我也一样_(:3」∠)_
推测是之前版本使用了 `System.Drawing` 导致的问题, 自2月份已改为使用 `SkiaSharp` , 此问题应已解决, 先行关闭
