### ISSUE TITLE
不支持mirai-api-http 1.9.0-dev-1

### ISSUE THREAD

**Issue by s158298261** [Executor-Cheng/Mirai-CSharp#26]
前两天miari群里发布了新的mirai-api-http 1.9.0  。 想尝鲜试一下。结果一启动报错。“给定关键字不在字典中”。

**Comment by Executor-Cheng** [comment]
`/about`接口返回的信息有所变动。
原响应为
```json
{
    "code": 0,
    "errorMessage": "",
    "data": {
        "version": "v1.0.0"
    }
}
```
新的响应为
```json
{
    "data": {
        "version": "1.8.4"
    }
}
```
https://github.com/Executor-Cheng/Mirai-CSharp/blob/365c79f8bb213322e02017501975cf37178ec3de/Mirai-CSharp/Session/MiraiHttpSession.Authentication.cs#L108
本行按照以前的规范会固定获取`$.code`属性判断api返回是否正常, 由于新版返回没有这个`$.code`, 所以抛了个`System.Collections.Generic.KeyNotFoundException`。
如果`mirai-api-http`v1.9.0正式发布时此接口返回未更改的话, 我就会修掉它。

**Comment by Executor-Cheng** [comment]
补充一句, 你也可以自己先行改下本项目源码, 修改`MiraiHttpSession.GetVersionAsync(HttpClient, MiraiHttpSessionOptions)`方法如下:
```csharp
public static async Task<Version> GetVersionAsync(HttpClient client, MiraiHttpSessionOptions options)
{
    using JsonDocument j = await client.GetAsync($"{options.BaseUrl}/about").GetJsonAsync();
    JsonElement root = j.RootElement;
    if (!root.TryGetProperty("code", out JsonElement codeToken) || codeToken.GetInt32() == 0)
    {
        string version = root.GetProperty("data").GetProperty("version").GetString()!;
        int vIndex = version.IndexOf('v');
#if NETSTANDARD2_0
        return Version.Parse(vIndex > 0 ? version.Substring(vIndex) : version); // v1.0.0 ~ v1.7.2, skip 'v'
#else
        return Version.Parse(vIndex > 0 ? version[vIndex..] : version); // v1.0.0 ~ v1.7.2, skip 'v'
#endif
    }
    throw GetCommonException(codeToken.GetInt32(), in root);
}
```

**Comment by s158298261** [comment]
好的，非常感谢！

**Comment by Executor-Cheng** [comment]
> 好的，非常感谢！

@s158298261 我发现这个code缺键的地方不止一处了, 建议你使用一下`release/v1.0.2.2`分支来重新build本项目

**Comment by aion1998** [comment]
啊这，我懂了，我自己改下，其实就是封装了那个api请求

**Comment by ryuujo1573** [comment]
这个部分是否已经修复？我在使用1.10.0版本的http api，没有遇到以上问题

**Comment by Executor-Cheng** [comment]
> 这个部分是否已经修复？我在使用1.10.0版本的http api，没有遇到以上问题

已经修复, 版本更新后统一close
