### ISSUE TITLE
处理加群申请时获取加群问题的回答

### ISSUE THREAD

**Issue by developer-ken** [Executor-Cheng/Mirai-CSharp#27]
是否有办法在处理加群申请时获取加群问题的回答？

我通过Mirai-CSharp操作Mirai，现在希望能够在处理加群时获取用户对加群问题的回答，并以此判定是否同意。请问是否已经可行，或是否有可能在未来可行？

我曾在mirai提交过同样的issue:
https://github.com/mamoe/mirai/issues/697

**Comment by Executor-Cheng** [comment]
可行, 稍后我会在nuget上边发一版`preview.2`, 敬请留意
