### ISSUE TITLE
获得指定QQ用户的当前等级

### ISSUE THREAD

**Issue by developer-ken** [Executor-Cheng/Mirai-CSharp#28]
我希望能够获得正在加入群聊的QQ用户的当前等级，并用以作为决定是否允许加入群聊的一部分条件。
能否增加获取等级的接口或在加群事件的返回值中取得等级？

**Comment by Executor-Cheng** [comment]
找了一圈`mirai-api-http`的文档, 并未发现有一个api能拿给定QQ的等级信息。
并且申请入群事件也没有提供你所需要的申请人QQ等级。
申请如群事件的json如下:
```json
{
    "type": "MemberJoinRequestEvent",
    "eventId": 12345678,
    "fromId": 123456,
    "groupId": 654321,
    "groupName": "Group",
    "nick": "Nick Name",
    "message": ""
}
```
所以很抱歉, 暂时无法实现。

**Comment by developer-ken** [comment]
该功能已被Mirai实现，我已向api-http项目提交issue
https://github.com/project-mirai/mirai-api-http/issues/536
