### ISSUE TITLE
关于实现和操作问题

### ISSUE THREAD

**Issue by baka-gourd** [Executor-Cheng/Mirai-CSharp#3]
在`public partial class Plugin`时，如果不继承IGroupMessage，就无法通过AddPluign添加：提示从“BotMirai Plugin"转换为“Miral_CSharp.Plugin. IPlugin"，从而无法工作；但在继承后Resharper告诉我`Interface member Task bools Mirai_CSharp.Plugin.lPlugin-lGroupMessageEventArgs> .HandieEventi(MiraiHttpSession, IGroupMessageEventArgs)" is not implemented`虽然能够运行，但仍是红线。
就个人使用情况看，现在必须手动挂载到指定事件才能够解决。

**Comment by Executor-Cheng** [comment]
能贴一下你Plugin是怎么继承/实现的嘛

**Comment by Executor-Cheng** [comment]
其实我怀疑是你的Resharper不支持C# 8.0中的`默认接口实现`特性, 在`Plugin\Interface`下的所有接口均已默认实现了`IPlugin<TEventArgs>.HandleEvent(MiraiHttpSession, TEventArgs)`, 按理来说不应该报接口未实现的错误

**Comment by baka-gourd** [comment]
``` C#
    public partial class Plugin : IGroupMessage
    {
        public async Task<bool> GroupMessage(MiraiHttpSession session, IGroupMessageEventArgs e)
        {
            if (e.Chain[1].ToString().Contains("114514"))
                await session.SendGroupMessageAsync(e.Sender.Group.Id,
                    new IMessageBase[] {new PlainMessage(e.Chain[1].ToString())});
            if (e.Sender.Group.Id == **********)
            {
                if (e.Sender.Permission == GroupPermission.Member)
                {
                    var str = e.Chain[1].ToString();
                    //净化网络环境
                    if (str.Contains("草") && !str.Contains("生"))
                    {
                        var reg = new Regex(@"[1-9]\d*");
                        var catchNum = reg.Match(e.Chain[0].ToString());
                        await session.RevokeMessageAsync(int.Parse(catchNum.Value));
                    }
                    else if (str.Contains("nmsl"))
                    {
                        var reg = new Regex(@"[1-9]\d*");
                        var catchNum = reg.Match(e.Chain[0].ToString());
                        await session.RevokeMessageAsync(int.Parse(catchNum.Value));
                        await session.MuteAsync(e.Sender.Id, e.Sender.Group.Id, new TimeSpan(0, 1, 0));
                    }
                }
            }
            else if (e.Sender.Group.Id == **********)
            {
                var str = e.Chain[1].ToString();
                if (str.Contains("来张色图"))
                {
                    var msg = await session.UploadPictureAsync(PictureTarget.Group, @"./1.jpg");
                    var chain = new IMessageBase[] {msg};
                    await session.SendGroupMessageAsync(e.Sender.Group.Id, chain);
                }
            }
            return false;
        }
    }
```

在实际过程中，只能继承IGroupMessage，继承IPlugin不管是实际上和源码上都不成立；若不继承，则是类型转换失败。
至于resharper的红线问题，是在最后一次更新后出现的（最近jb更新都在开倒车的感觉），可能是他不支持了吧。

**Comment by Executor-Cheng** [comment]
> 在实际过程中，只能继承IGroupMessage，继承IPlugin不管是实际上和源码上都不成立；若不继承，则是类型转换失败。

`IFriendMessage`的接口你试过嘛
`IPlugin`并不应该直接用于插件实现，`IPlugin<TEventArgs>`才是插件应该实现的接口，`IGroupMessage`实际上继承了`IPlugin<IGroupMessageEventArgs>`接口，并且为其提供了一个默认的`HandleEvent`实现
如果你插件需要自己实现`IPlugin<TEventArgs>`接口的话，你需要在类中实现其`HandleEvent`方法，举例:
```CSharp
public class ExamplePlugin : IPlugin<IFriendMessageEventArgs>
{
    public Task<bool> HandleEvent(MiraiHttpSession session, IFriendMessageEventArgs e)
        => Task.FromResult(false);
}
```

**Comment by baka-gourd** [comment]
再来问一个问题，在mirai-http中写道：
``` Json
{
    "type": "Image",
    "imageId": "{01E9451B-70ED-EAE3-B37C-101F1EEBF5B5}.mirai", 
    "url": "http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "path": null
}
```
说明http是返回图片原链接的，在c#中该如何获取，或者是还未实现

**Comment by baka-gourd** [comment]
有时间给这项目试着写个wiki :thinking:

**Comment by Executor-Cheng** [comment]
> 再来问一个问题，在mirai-http中写道：
> 
> ```json
> {
>     "type": "Image",
>     "imageId": "{01E9451B-70ED-EAE3-B37C-101F1EEBF5B5}.mirai", 
>     "url": "http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
>     "path": null
> }
> ```

无论是好友`IFriendMessageEventArgs`/群`IGroupMessageEventArgs`/临时消息`ITempMessageEventArgs`, 它们都继承了`ICommonMessageEventArgs`接口, 这个接口里边有个`Chain`属性表示消息链, 所以你只需要`e.Chain.OfType<ImageMessage>()`一下, 你就能拿到这个消息链里边所有的图片了。你把泛型参数换一换还可以获取其它类型的消息, 所有类型见 [MessageBase.cs](https://github.com/Executor-Cheng/Mirai-CSharp/blob/master/Mirai-CSharp/Models/MessageBase.cs)
Wiki还没玩过, 迟点我去研究一下, 这个Issue我就先关了, 有新的问题可以随时开新的Issue。
