### ISSUE TITLE
关于UploadPictureAsync对图片流格式的问题

### ISSUE THREAD

**Issue by fsjgd** [Executor-Cheng/Mirai-CSharp#30]
通过WebRequest.Create(url).GetResponse().GetResponseStream()获取的图片流传入UploadPictureAsync会在imgStream.Seek(0, SeekOrigin.Begin);处报Specified method is not supported. 然后我注释了Seek这句, 接着它又在PostAsync处报'u' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

尝试过将图片下载到本地然后用FileStream读取传进来是没有问题的.
也试了把Image.Save进MemorySteam, 然后传进来, 这样的话消息发的出去, 但是图片是裂图.
互联网上的图片, 不想经过硬盘, 有没有什么处理方式?

Mirai-CSharp版本1.0.2.1
mirai-api-http版本1.9.5

**Comment by Executor-Cheng** [comment]
参考 mamoe/mirai#797。这个问题是`mirai`的一个regression issue
建议使用`2.0-M1-1`版本的`mirai`和`mirai-console`, 搭配`v1.9.2`的`mirai-api-http`
不过意外的我也发现这个`InternalUploadPictureAsync`方法有问题, 之后我会发一版`preview3`

**Comment by Executor-Cheng** [comment]
mamoe/mirai@901c8b5 已经解决图片上传问题
