### ISSUE TITLE
有没有办法获取自己的信息呢

### ISSUE THREAD

**Issue by KevinZonda** [Executor-Cheng/Mirai-CSharp#35]
我看了下 `MiraiHttpSession`，似乎并没有能够获取自己信息的方法呢...

**Comment by Executor-Cheng** [comment]
应该是没有方法的, 本项目基于`mirai-api-http`提供的api进行编写, 其实现的功能本项目才能实现
参考: [README](https://github.com/project-mirai/mirai-api-http/blob/master/README.md)
