### ISSUE TITLE
示例程序session.ConnectAsync时发生错误

### ISSUE THREAD

**Issue by aion1998** [Executor-Cheng/Mirai-CSharp#36]
错误详情：
![image](https://user-images.githubusercontent.com/19725014/106102691-b5447900-617a-11eb-9d05-ec70de45b667.png)

具体发生错误地点在下图红线所画区域
![image](https://user-images.githubusercontent.com/19725014/106102660-ad84d480-617a-11eb-9ebe-d0aa5a1fc788.png)

编辑器：VS2019

**Comment by Executor-Cheng** [comment]
麻烦提供下所用的`mirai-api-http`版本

**Comment by aion1998** [comment]
> 麻烦提供下所用的`mirai-api-http`版本

![image](https://user-images.githubusercontent.com/19725014/106120989-01e77e80-6192-11eb-9fd2-1e967b440501.png)

**Comment by aion1998** [comment]
> 麻烦提供下所用的`mirai-api-http`版本

1111,如图

**Comment by Executor-Cheng** [comment]
v1.9.6的`mirai-api-http`在本项目最新**!预览!**版本是没问题的
检查一下你nuget的时候是不是没勾`包括预发行版`的选项
