### ISSUE TITLE
IMessageBase 数组过多发送失败率99%

### ISSUE THREAD

**Issue by aion1998** [Executor-Cheng/Mirai-CSharp#37]
IMessageBase[] 集合要是超过五个以上 new PlainMessage  几乎不可能发送成功，昨天反复测试也只成功发成功了一次

-。- 虽然说还是可以new 一个然后全塞里面，但是就好奇为啥多个（五个起步）new PlainMessage 就不行，我还调了下源码，传参啥的也没啥问题噻，接口返回的也是okay，奇奇怪怪

**Comment by Executor-Cheng** [comment]
那么这大概率是mirai的问题了, 如果你的版本是2.2.0且此问题仍然存在的话, 就去mirai那边开个issue吧
(点我去开issue)[https://github.com/mamoe/mirai/issues/new?assignees=&labels=question&template=bug.md&title=]
