### ISSUE TITLE
关于图片接收问题

### ISSUE THREAD

**Issue by aion1998** [Executor-Cheng/Mirai-CSharp#38]
我想能够接收消息的时候能拿到图片的流，然后让我自己去操作后续（上传到云平台，存本地，等等各种操作）

这个我该咋整，这个api项目文档没看到相关说明，想在这个SDK里问问作者

**Comment by Executor-Cheng** [comment]
由于`mirai-api-http`仅仅返回了图片的url, 因此需要你手动创建http请求并且获取它的响应流
