### ISSUE TITLE
有获取缓存的消息这个接口吗?

### ISSUE THREAD

**Issue by dawn-lc** [Executor-Cheng/Mirai-CSharp#39]
[通过messageid获取一条被缓存的消息](https://github.com/project-mirai/mirai-api-http/blob/master/docs/API.md#%E9%80%9A%E8%BF%87messageid%E8%8E%B7%E5%8F%96%E4%B8%80%E6%9D%A1%E8%A2%AB%E7%BC%93%E5%AD%98%E7%9A%84%E6%B6%88%E6%81%AF)

**Comment by dawn-lc** [comment]
```
        /// <summary>
        /// 异步通过给定的ID获取信息
        /// </summary>
        /// <param name="MessageId">要获取信息的ID</param>
        public Task<ICommonMessageEventArgs> GetMessageAsync(int MessageId)
        {
            InternalSessionInfo session = SafeGetSession();
            return session.Client.GetAsync($"{session.Options.BaseUrl}/messageFromId?sessionKey={session.SessionKey}&id={MessageId}", session.Token)
                .AsApiRespAsync<ICommonMessageEventArgs, CommonMessageEventArgs>(session.Token);
        }
```
我尝试实现这个接口但是,并没有奏效.
这是错误信息
Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Mirai_CSharp.Models.CommonMessageEventArgs'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.

**Comment by Executor-Cheng** [comment]
我来写吧, `CommonMessageEventArgs`这个是个抽象基类来的, 不能直接这么玩
