### ISSUE TITLE
mirai-console更新后GetFriendListAsync方法无法获取到好友列表

### ISSUE THREAD

**Issue by fsjgd** [Executor-Cheng/Mirai-CSharp#40]
mirai-console版本2.4-M1
mirai-api-http版本1.9.8
Mirai-CSharp版本1.0.2.2Release
GetFriendListAsync方法返回空集合

**Comment by Executor-Cheng** [comment]
这个问题我自己暂时没法复现, 你需要确定调用`mirai-api-http`接口时响应的正文内容是啥
你可能需要clone本项目, 直接在你的项目中添加本项目引用, 使用debug环境编译并运行, 在以下地方下断点步进看看响应正文是什么样子:
https://github.com/Executor-Cheng/Mirai-CSharp/blob/365c79f8bb213322e02017501975cf37178ec3de/Mirai-CSharp/Session/MiraiHttpSession.Management.cs#L22

**Comment by fsjgd** [comment]
响应正文
Id = 66, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"

**Comment by Executor-Cheng** [comment]
你这是个异步Task来的。。
先把分支切换到`preview/1.0.2.2`,在上文Line22处断点, 等运行断下后再在这个地方下一个断点
https://github.com/Executor-Cheng/Mirai-CSharp/blob/76108a97b382354cd12668752e96ec301f47cdf1/Mirai-CSharp/Extensions/ApiResponseExtensions.cs#L48
然后把root的内容用邮件发过来我看看
exprotected@outlook.com

**Comment by fsjgd** [comment]
回邮件了
[http://mail.163.com/js6/s?func=mbox:getMessageData&mid=461:xtbBzQk1gV0CPURjHQACsq&part=3](url)
[http://mail.163.com/js6/s?func=mbox:getMessageData&mid=461:xtbBzQk1gV0CPURjHQACsq&part=4](url)

**Comment by Executor-Cheng** [comment]
似乎没看到你的邮件, 试试发送到以下邮箱
exprotected@vip.qq.com

**Comment by Executor-Cheng** [comment]
好的, 从这方面来看, 不是本项目导致的问题
我帮你去反馈一下这个问题

**Comment by Executor-Cheng** [comment]
还有个问题, mirai-core的版本号也一起报一下吧

**Comment by fsjgd** [comment]
额, 应该也是这个版本
2.4-M1
libs文件夹下最新的是这几个
mirai-core-all-2.4-M1.jar
mirai-console-2.4-M1.jar
mirai-console-terminal-2.4-M1.jar
或者
config.json下是这样的
"packages": [
    {
      "id": "net.mamoe:mirai-console",
      "channel": "stable",
      "version": "2.4-M1",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-console-terminal",
      "channel": "beta",
      "version": "2.4-M1",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-core-all",
      "channel": "beta",
      "version": "2.4-M1",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-api-http",
      "channel": "stable",
      "version": "1.9.8",
      "type": "plugins"
    },
用mirai-console-loader自动更新的, 我也不是很确定是什么版本

**Comment by Executor-Cheng** [comment]
把mirai三件套更新到2.4-RC试试吧, 刚试了没问题

**Comment by fsjgd** [comment]
可以了, 谢谢大佬
