### ISSUE TITLE
GetGroupMemberInfoAsync会引发异常

### ISSUE THREAD

**Issue by ghj123h** [Executor-Cheng/Mirai-CSharp#46]
RT。
应该是因为`memberInfo`请求没有`code`状态码所致。

**Comment by Executor-Cheng** [comment]
`mirai-api-http`v1.9.8
`Mirai-CSharp`v1.0.2.2-preview.4
未能复现问题, 请提供你的这两项版本号

**Comment by ghj123h** [comment]
> 
> 
> `mirai-api-http`v1.9.8
> `Mirai-CSharp`v1.0.2.2-preview.4
> 未能复现问题, 请提供你的这两项版本号

`mirai-api-http`v1.7.4; `Mirai-CSharp` v1.0.2.0

**Comment by Executor-Cheng** [comment]
尝试把`Mirai-CSharp`更新到最新的**预览**版本
在最新的预览版本中, 已经解决`mirai-api-http`返回的json中没有`$.code`键的问题
参考`Mirai_CSharp.Extensions.ApiResponseExtensions.AsApiRespAsync<TResult, TImpl>(this Task<HttpResponseMessage>, CancellationToken)`
解决了问题就顺手close下本issue吧, 没有解决可以继续追问
