### ISSUE TITLE
根据Example写，部署linux后，cpu占用90%+

### ISSUE THREAD

**Issue by qinko233** [Executor-Cheng/Mirai-CSharp#50]
首先非常感谢作者提供的项目，让我这个小白也能顺利写qqbot来用。
# 问题描述
关于这个Example main函数里的死循环
https://github.com/Executor-Cheng/Mirai-CSharp/blob/365c79f8bb213322e02017501975cf37178ec3de/Mirai-CSharp.Example/Program.cs#L24
我在部署CentOS7之后 cpu占用一直高居90%+，但是自己在vs调试又是正常的。
# 解决
[百度到的办法](https://blog.csdn.net/Brouce__Lee/article/details/81109897)
办法就是在循环里加一行 `Thread.Sleep(1000);`
```
   while (true)
   {
        Thread.Sleep(1000);
         if (await Console.In.ReadLineAsync() == "exit")
         {
              return;
         }
    }
```
希望能帮助到同样遇到这个问题的盆友。。<del>(是我太菜了)</del>

**Comment by Executor-Cheng** [comment]
有可能是`await Console.In.ReadLineAsync()`立即返回了
下个版本解决
