### ISSUE TITLE
如何发送Quote消息？

### ISSUE THREAD

**Issue by ryuujo1573** [Executor-Cheng/Mirai-CSharp#52]
请求添加一个回复消息的案例
![image](https://user-images.githubusercontent.com/16525512/120813892-ec8bc200-c580-11eb-8890-7c4687501745.png)
这里的messageId是什么？在代码中如何获取？
感谢您的贡献！

**Comment by Executor-Cheng** [comment]
在你收到的消息链中会有一个类型为`SourceMessage`的消息, 其中有个`Id`属性
这个就是你想要的`messageId`
