### ISSUE TITLE
使用示例中的程序不能正常连接啊

### ISSUE THREAD

**Issue by Artectek** [Executor-Cheng/Mirai-CSharp#59]
提示错误：The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.”

**Comment by Artectek** [comment]
http插件是mirai-api-http-v2.2.0.mirai版本的，mirai-csharp是1.0.2.1版本。

**Comment by Executor-Cheng** [comment]
正常, preview/2.0.0 分支已经支持最新版本的 mirai-api-http 了, 不过我还没有改好示例, 预计今晚搞定

**Comment by Artectek** [comment]
好的多谢，那现在版本的支持什么版本的mirai-api-http呐

**Comment by Executor-Cheng** [comment]
> 好的多谢，那现在版本的支持什么版本的mirai-api-http呐

< 2.0.0
且掉线事件不触发是已知问题, 已在最新分支修复
