### ISSUE TITLE
。。新版本我有点懵逼

### ISSUE THREAD

**Issue by aion1998** [Executor-Cheng/Mirai-CSharp#62]
![image](https://user-images.githubusercontent.com/19725014/134795357-e68e1d3c-9681-46d3-8203-f7490388d694.png)

如图，我要咋整

**Comment by Executor-Cheng** [comment]
在 `ConfigureServices(IServiceCollection)` 中, 不需要用户自行构建 `IServiceProvider` 对象
所以你只需要 `services.AddMiraiBaseFramework()....` 然后把最后两行删掉即可

**Comment by aion1998** [comment]
好的，谢谢，爱你，mua~💓
