### ISSUE TITLE
nuget是不是没有最新版本？

### ISSUE THREAD

**Issue by aion1998** [Executor-Cheng/Mirai-CSharp#63]
![image](https://user-images.githubusercontent.com/19725014/134802310-ee9a241e-a3bf-43f7-88c7-0f4d0c0d8d5f.png)

![image](https://user-images.githubusercontent.com/19725014/134802317-4b72df6d-7779-434d-bbac-575c3d0983f6.png)

如图，找不着

**Comment by Executor-Cheng** [comment]
第一张图搜索框旁边有个 `包括预发行版`, 打勾再搜即可

**Comment by aion1998** [comment]
啊这，草率了，感谢

**Comment by aion1998** [comment]
> 啊这，草率了，感谢



> 第一张图搜索框旁边有个 `包括预发行版`, 打勾再搜即可

哎，升级版本了还不行
