### ISSUE TITLE
有没有全局设置机器人所有事件只响应指定群

### ISSUE THREAD

**Issue by aion1998** [Executor-Cheng/Mirai-CSharp#66]
例如我设置了机器人只响应：xxx群

之后所有的事件就只有在该群才会响应

**Comment by Executor-Cheng** [comment]
办不到, 只要是 `mirai-api-http` 通过ws推送过来的消息, `MiraiHttpSession` 总是会解析它们到具体的消息类, 并且调用相匹配的消息处理方法
你可以第一个注册将用于拦截非给定群消息的消息处理方法, 不满足条件直接设置 `e.BlockRemainingHandlers = true` 阻断消息传递 
也可以参考本项目的消息框架自己再写一套来推送所需要的消息

**Comment by aion1998** [comment]
好滴，明白了，感谢！
