### ISSUE TITLE
关于2.0版本的连接方式

### ISSUE THREAD

**Issue by dellbeat** [Executor-Cheng/Mirai-CSharp#69]
按照项目mirai-api-http2.0+的连接方式 是把http和ws分离开了
但是看Mirai-CSharp项目源码似乎还是http认证连接然后ws负责接收消息？
还请解惑

**Comment by Executor-Cheng** [comment]
哪里有分离开
mirai-api-http v1.x的时代就只有ws来着, http负责鉴权和机器人操作
v2.0时花样才多, ws, 反向ws, webhook之类的

**Comment by dellbeat** [comment]
1.x的时候http是支持消息轮询的 有消息轮询的API（2.x实际也是 就是感觉http轮询效率不太行）
2.x的话ws可以和http一样发各种请求了【音视频文件的还不支持】 所以以为Mirai-CSharp会有**支持ws发送各类请求**
不过刚刚再去mirai-api-http看了一下2.x能支持多adapter控制同一session 那应该也没问题
