### ISSUE TITLE
SendGroupMessageAsync性能

### ISSUE THREAD

**Issue by mydeariesue** [Executor-Cheng/Mirai-CSharp#7]
SendGroupMessageAsync耗时超过2400ms以上，是否可优化？

**Comment by Executor-Cheng** [comment]
![批注 2020-08-15 190617](https://user-images.githubusercontent.com/27953325/90311122-7c954800-df2a-11ea-972c-74956a11bc2b.png)
我自己在Debug环境下测试发送只用了518ms, Release环境下缩短为314ms, 你可能得发一些代码片段出来

**Comment by mydeariesue** [comment]
我将keepalive取消之后，httprequest性能就正常了

**Comment by Executor-Cheng** [comment]
嗯，下次我换成`HttpClient`好了
