### ISSUE TITLE
发送艾特人的消息发送一直失败

### ISSUE THREAD

**Issue by aion1998** [Executor-Cheng/Mirai-CSharp#73]
![image](https://user-images.githubusercontent.com/19725014/138844640-1cd14ed9-6b2a-47f5-8873-17ada74e9165.png)

如图，单单发文字消息没问题，但是加上atmessage就不行了，也就是注释的那部分

**Comment by Executor-Cheng** [comment]
@aion1998 `2.0.0-rc.2`版本将于今天下午3点发布到nuget上, `2.0.0`正式版将在7天后发布, 如你希望你的问题被尽快解决, 请尽快回复一下, 感谢

**Comment by aion1998** [comment]
好滴，俺试试

**Comment by aion1998** [comment]
逮到：
![image](https://user-images.githubusercontent.com/19725014/139612012-8cb8c65c-8fee-4195-879e-885f2d276767.png)

**Comment by aion1998** [comment]
这是测试代码：
![image](https://user-images.githubusercontent.com/19725014/139612102-71b2a6ad-2458-46ab-a3f6-0c15587a4bb8.png)

**Comment by Executor-Cheng** [comment]
如果你现在在用的是`rc.1`版本的话, 并且确认机器人在群内没有受到发言限制的话
可否麻烦你引用一下本项目源码, 在`ApiResponseExtensions.EnsureApiRespCode`处下一个断点查看 `mirai-api-http` 返回的具体错误json?
之前我自行测试的时候, 在确保了构建 `AtMessage` 时, 传入的qq号有效的情况下, 未能复现本问题

**Comment by aion1998** [comment]
还有SendImageToGroupAsync方法也有异常
调用代码：
![image](https://user-images.githubusercontent.com/19725014/139612493-923a06d3-f205-4c52-8bec-0acf782796d8.png)
异常信息：
![image](https://user-images.githubusercontent.com/19725014/139612561-7528169a-895d-4821-bbb1-d85afc7ecd91.png)

**Comment by aion1998** [comment]
> 如果你现在在用的是`rc.1`版本的话, 并且确认机器人在群内没有受到发言限制的话 可否麻烦你引用一下本项目源码, 在`ApiResponseExtensions.EnsureApiRespCode`处下一个断点查看 `mirai-api-http` 返回的具体错误json? 之前我自行测试的时候, 在确保了构建 `AtMessage` 时, 传入的qq号有效的情况下, 未能复现本问题

好，俺试试

**Comment by Executor-Cheng** [comment]
调用 `SendImageToGroupAsync` 时发生异常的原因已经确认, 感谢反馈
但是对先前的问题, 刚刚我再次尝试了, 未能成功复现
你可以看看是不是 `e.Sender.Group.Id` 为0

**Comment by aion1998** [comment]
引用源码遇到蛋疼的问题
![image](https://user-images.githubusercontent.com/19725014/139613919-2bca4457-2275-4955-8f11-f063208cb3f4.png)


e.Sender.Group.Id，和e.Sender.Id 没有一个是 0的，都是正常的号码

**Comment by Executor-Cheng** [comment]
打开根目录下的 `Directory.Build.props`
移除 `TargetFrameworks` 里边的 `net6.0;` 即可
如果两个都不是0的话, 有可能就是 `mirai-api-http` 的bug了, 你可以考虑将它更新到 `v2.3.1+`

**Comment by aion1998** [comment]
俺就是mirai-api-http-v2.3.1.mirai.jar

**Comment by aion1998** [comment]
![image](https://user-images.githubusercontent.com/19725014/139620030-ca2ddbbd-0e3c-4d77-a53a-08bced0a19d2.png)
这个就是 `  await session.SendGroupMessageAsync(e.Sender.Group.Id, new Mirai.CSharp.HttpApi.Models.ChatMessages.PlainMessage("呼啦啦，呼啦啦，大家好我是王尼玛"), new Mirai.CSharp.HttpApi.Models.ChatMessages.AtMessage(e.Sender.Id)); `

发送消息时候最后的入参数据

![image](https://user-images.githubusercontent.com/19725014/139620092-014e13e9-2386-480b-ab65-61c13537b08c.png)

=。= 这消息链咋看实际内容喔

**Comment by aion1998** [comment]
返回：
![image](https://user-images.githubusercontent.com/19725014/139620206-b8ece7bc-0fb5-4596-b2bf-e52a43946bb9.png)

**Comment by Executor-Cheng** [comment]
在你的断点处用监视实时计算一下以下语句
`JsonSerializer.Serialize(payload, _chatMessageSerializingOptions)`

**Comment by aion1998** [comment]
输出内容如下
```
"{\"sessionKey\":\"KnxTfER9\",\"qq\":null,\"group\":572166536,\"quote\":null,\"messageChain\":[{\"type\":\"Plain\",\"text\":\"\\u547C\\u5566\\u5566\\uFF0C\\u547C\\u5566\\u5566\\uFF0C\\u5927\\u5BB6\\u597D\\u6211\\u662F\\u738B\\u5C3C\\u739B\"},{\"type\":\"At\",\"target\":1075858260,\"display\":null}]}"
```

**Comment by Executor-Cheng** [comment]
输出是完全符合规范的
我估计这个问题应该不是本项目的问题, 像是mirai那边的缓存失效导致at目标不存在
你试一试重启mirai本体
