### ISSUE TITLE
At事件报错

### ISSUE THREAD

**Issue by aion1998** [Executor-Cheng/Mirai-CSharp#82]
错误原因：
![image](https://user-images.githubusercontent.com/19725014/139806296-bd0de851-259d-4904-8969-226bd43087f7.png)

运行时各值：
![image](https://user-images.githubusercontent.com/19725014/139806420-cbe1b29a-8c5c-45c8-b5c6-776d01a977e3.png)

> 就一个单独的发了一个AtMessage，没有其他东西

mirai版本：
![image](https://user-images.githubusercontent.com/19725014/139806689-d33c8155-3685-4439-86af-946e4450d30c.png)

**Comment by Executor-Cheng** [comment]
我感觉这个不是本项目的问题
你可以试试重启一次mirai
如果还是未能解决，尝试换几个at目标看看
