### ISSUE TITLE
找不到“修改群员管理员”的接口

### ISSUE THREAD

**Issue by dellbeat** [Executor-Cheng/Mirai-CSharp#86]
在目前的MAH文档中，有一个[修改群员管理员](https://docs.mirai.mamoe.net/mirai-api-http/api/API.html#%E4%BF%AE%E6%94%B9%E7%BE%A4%E5%91%98%E7%AE%A1%E7%90%86%E5%91%98)的接口 但是在preview/2.0.0分支内没有找到使用该接口的代码
所以想确认一下是不是没有该接口 如果没有希望能添加进去 谢谢

**Comment by Executor-Cheng** [comment]
已在 Executor-Cheng/Mirai-CSharp@202c4690 中实现
正式版今晚发布

**Comment by dellbeat** [comment]
好的 那就等晚上拉一下代码 issue先关了
