### ISSUE TITLE
关于发送群消息图片无法正常发送的问题

### ISSUE THREAD

**Issue by dellbeat** [Executor-Cheng/Mirai-CSharp#89]
有可能是`用法有误 `但是不太确定 我把具体细节列一下

场景：发送群消息
发送方法：
1.使用{guid}.mirai 无效（这个是已经接收到图片并将该图片再次发送出去）
2.使用腾讯图片服务器的图片地址 无效
3.使用本地路径发送 无效

其中发送过程是这样的：不经过`UploadPictureAsync`接口，直接实例化`ImageMessage`,并对对应属性进行赋值，后续组合成消息链数组发送

附带http请求报文和回复

`{"sessionKey":"jRarU388","qq":null,"group":xxx,"quote":null,"messageChain":[{"type":"Image","imageId":"{B33D0D9A-220C-201A-6ADF-E44A8A7E1556}.jpg","url":null,"path":null}]}`

`{"code":0,"msg":"success","messageId":-1}`

不知道是不是我调用方法有误（即必须经过`UploadPictureAsync`接口 但是方法1应该不需要再经过此才对）

**Comment by Executor-Cheng** [comment]
今天醒了再调查一下
写了一晚上的silk4j, 看那堆C源码已经麻了, 好在是完工了

**Comment by dellbeat** [comment]
> 今天醒了再调查一下 写了一晚上的silk4j, 看那堆C源码已经麻了, 好在是完工了

23333 辛苦了 我这边不是很着急

**Comment by dellbeat** [comment]
但是目前升级core版本了似乎就不复现了 可能修复了

**Comment by dellbeat** [comment]
> 今天醒了再调查一下 写了一晚上的silk4j, 看那堆C源码已经麻了, 好在是完工了

写silk4j?今天似乎看到了这个项目 是准备写给C#调用的转语音接口么

**Comment by Executor-Cheng** [comment]
我就说不应该是我参数给得不正确的问题(〜￣△￣)〜
是的, 还差导出函数的签名设计问题, 我会另起一个项目来存放这些代码
这里下一个版本会用这个库来检查是否需要先转换mp3到silk

**Comment by dellbeat** [comment]
> 我就说不应该是我参数给得不正确的问题(〜￣△￣)〜 是的, 还差导出函数的签名设计问题, 我会另起一个项目来存放这些代码 这里下一个版本会用这个库来检查是否需要先转换mp3到silk

可以可以 到时看看转换的音质效果咋样 今天折腾过把mp3转silk 但是音质确实一言难尽（从3.41Mb压到300多K）

**Comment by dellbeat** [comment]
作者大大辛苦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月16日(周二) 凌晨1:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Executor-Cheng/Mirai-CSharp] 关于发送群消息图片无法正常发送的问题 (Issue #89)




 
silklame 项目已经发布了
 这边会尽快跟进一下
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
