### ISSUE TITLE
GroupMemberInfo实体属性有添加

### ISSUE THREAD

**Issue by dellbeat** [Executor-Cheng/Mirai-CSharp#90]
目前用的是core的2.8.0和MAH的2.3.3

然后测试获取`GroupMemberInfo`实体的时候 发现属性有所添加

这个是内部实体序列化的结果
`{"Name":"XXX","Group":{"Permission":0,"Id":GroupNumber,"Name":"ABC"},"Permission":0,"Id":XXX}`

这个是MAH返回的响应
`{"id":XXX,"memberName":"XXX","specialTitle":"可能是三号","permission":"MEMBER","joinTimestamp":1635228220,"lastSpeakTimestamp":1635228220,"muteTimeRemaining":0,"group":{"id":GroupNumber,"name":"ABC","permission":"MEMBER"}}`

希望后续版本能支持一下

还有就是有没有考虑开放一个指定代理的接口或者方法，目前如果需要让请求走抓包应用需要自己去`Mirai-CSharp`项目源码内自行定义Http代理参数，对代码会有改动，后续可能会不方便

**Comment by Executor-Cheng** [comment]
`protected MiraiHttpSession(IServiceProvider, MiraiHttpSessionOptions, HttpClient, IMiraiHttpMessageHandlerInvoker)`
当初考虑了一下这种情况, 所以我留了一个这样的构造, 将来可以考虑改为public
这些新增属性当初我也见过, 当时没加上, 会考虑新增一个接口 `IGroupMemberExternInfo` 给用户使用这些属性

**Comment by dellbeat** [comment]
> `protected MiraiHttpSession(IServiceProvider, MiraiHttpSessionOptions, HttpClient, IMiraiHttpMessageHandlerInvoker)` 当初考虑了一下这种情况, 所以我留了一个这样的构造, 将来可以考虑改为public 这些新增属性当初我也见过, 当时没加上, 会考虑新增一个接口 `IGroupMemberExtraInfo` 给用户使用这些属性

目前的方法是添加了一个handler并改动了构造函数 具体如下所示

```
      static HttpClientHandler handler = new HttpClientHandler()
        {
            Proxy = new System.Net.WebProxy("http://127.0.0.1:8888"),
            UseProxy = true,
        };

        /// <summary>
        /// 初始化 <see cref="MiraiHttpSession"/> 类的新实例
        /// </summary>
        public MiraiHttpSession(IServiceProvider services, IOptions<MiraiHttpSessionOptions> options, IMiraiHttpMessageHandlerInvoker invoker) : this(services, options.Value, new HttpClient(handler), invoker)
        {
            
        }
```

**Comment by Executor-Cheng** [comment]
我当初的考量是让用户自行继承 `MiraiHttpSession` 来调用上边我提到的构造, 这样 `HttpClient` 就可以从DI里边拿出来了
我还是把这个构造做成public比较好, 既然是基于DI设计的, `HttpClient` 理应从DI中获取
