### ISSUE TITLE
上传群文件问题

### ISSUE THREAD

**Issue by dellbeat** [Executor-Cheng/Mirai-CSharp#91]
晚上调上传群文件接口发现的问题
1.少了`target`参数，无法正确上传文件，MAH会提示400
2.添加了`target`参数后，由于`StringContent.Headers.ContentDisposition`没有被实例化，如果直接对内部的`Name`赋值会报错
3.在`file`参数内输入的`ContentDisposition.FileName`是在上传文件成功后会看到的文件名，所以不应该直接调用`Guid.NewGuid().ToString("n")`，最好是能传本地文件路径进来，通过路径读取文件名

本来是想直接改现有方法，但是发现要加参数并且修改已有的，所以临时在内部增加了一个方法供自己使用，已经推到我fork的仓库了
[代码改动](https://github.com/dellbeat/Mirai-CSharp/commit/240c19ab356714563fd64423770ffc0aac76b7d6)
看看作者能不能参考着修改一下自己的项目

还有上传语音和图片的话时间原因没测 白天起来再说吧XD

**Comment by Executor-Cheng** [comment]
感谢反馈~
稍后我会开分支, 然后拉一下你那边的commit

**Comment by dellbeat** [comment]
好的 正好刚醒 我去调一下语音和图片上传看看XD

**Comment by dellbeat** [comment]
测试了一下上传图片没有问题 语音的话群聊侧也OK 好友侧的问题已经反馈给MAH了（不是本项目的问题）

**Comment by Executor-Cheng** [comment]
我大概也改完了, 不过自core v2.8.0起, 已禁止在用户侧直接发送 `FileMessage` (mamoe/mirai#1646), 导致mah无法上传群文件
估计等会儿我也得去mah那边开个issue了

**Comment by dellbeat** [comment]
> 我大概也改完了, 不过自core v2.8.0起, 已禁止在用户侧直接发送 `FileMessage` ([mamoe/mirai#1646](https://github.com/mamoe/mirai/issues/1646)), 导致mah无法上传群文件 估计等会儿我也得去mah那边开个issue了

我用的core就是2.8.0 但是可以上传 之前那个问题我也看过 似乎是不允许在转发消息的时候发送`FileMessage `
参考[现在是否支持发送File类型消息？](https://github.com/project-mirai/mirai-api-http/issues/494)

**Comment by Executor-Cheng** [comment]
我不行诶, 测试的时候捕获到一个 `UnknownResponseException`, mah给了我一个 `{"code":500,"msg":"Sending FileMessage is not in support"}`
后台那边我也看到了下图
![mah报错](https://user-images.githubusercontent.com/27953325/142752411-a6c93cce-6e70-41a9-ad45-95df91c5f884.png)
从这个调用堆栈来看, 多半就是mah的问题了
具体怎么测试的你可以来我破站直播间瞧一瞧, 2721650

**Comment by dellbeat** [comment]
我马上来看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月21日(星期天) 下午2:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Executor-Cheng/Mirai-CSharp] 上传群文件问题 (Issue #91)





 
我不行诶, 测试的时候捕获到一个 UnknownResponseException, mah给了我一个 {"code":500,"msg":"Sending FileMessage is not in support"}
 后台那边我也看到了下图
 
 从这个调用堆栈来看, 多半就是mah的问题了
 具体怎么测试的你可以来我破站直播间瞧一瞧, 2721650
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
