### ISSUE TITLE
部分ChatMessage的ToString疑问

### ISSUE THREAD

**Issue by dellbeat** [Executor-Cheng/Mirai-CSharp#97]
收到好友/群消息的消息链时，会将消息链tostring供日志记录用
即`{string.Join("", (IEnumerable<IChatMessage>)message.Chain)}")`
但是在诸如`ImageMessage`和`VoiceMessage`等消息类型里，是具有`url`属性的
目前没有办法直接将`url`属性通过以上方式显示出来

如果在不修改本项目源码的情况下 是否有方法能修改特定消息类型的tostring方法

（之前是修改过项目源码的 但是考虑到要跟新特性和bug修复 每次这么改多少有点麻烦）

**Comment by Executor-Cheng** [comment]
在我自己设计所有的ChatMessage类时, `ToString` 方法已重写至与 `mirai-console` 中打印出来的消息格式一致
现版本你可以继续继承 `*Message` 类, 然后使用 `AddMiraiHttpFramework` 从0开始创建所有的服务依赖
2.1.0版本我会将 `MiraiHttpFrameworkBuilder` 中的 `AddDefaultParsers`, `AddDefaultChatParsers` 改为虚方法, 届时你只需重写其中的 `AddDefaultChatParsers`, 将其中的所有类型参数改为你自己继承出来的消息类型即可

**Comment by dellbeat** [comment]
好的 了解了

**Comment by dellbeat** [comment]
刚刚试了一下 有两行代码显示自身方法有保护级别无法调用

```
TryAddService(typeof(IMiraiHttpMessageJsonOptionsFactory), typeof(MiraiHttpMessageJsonOptionsFactory), ServiceLifetime.Singleton, out _); // 解析消息链所必须的服务
TryAddService(typeof(IMiraiHttpMessageJsonOptions<>), typeof(MiraiHttpMessageJsonOptions<>), ServiceLifetime.Singleton, out _); // 同上
```

是否有等价方法可以调用

**Comment by Executor-Cheng** [comment]
实际上是封装了对 `IServiceCollection.TryAddEnumerable` 的调用
用 `builder.Services.TryAddEnumerable(new ServiceDescriptor(typeof(IMiraiHttpMessageJsonOptionsFactory), typeof(MiraiHttpMessageJsonOptionsFactory), ServiceLifetime.Singleton))` 即可
对你请求的功能已经完成实现, 参考 Executor-Cheng/Mirai-CSharp@23b3804, #98

**Comment by dellbeat** [comment]
好的明白了 我先拉一下你的改动再试试

**Comment by dellbeat** [comment]
在尝试继承`MiraiHttpFrameworkBuilder`并重写了`AddDefaultParsers`方法之后
遇到了一些问题

关联代码是这样的
```
                //var builder = servicesCol.AddMiraiBaseFramework();
                var builder = new MiraiHttpFrameworkCustomBuilder(servicesCol);

                foreach (IMiraiMessageHandler typeInstance in handlers)//将所有handler通过Bulider接入framework
                {
                    builder.AddHandler(typeInstance);
                }
```

然后给的错误提示是
`无法从“Mirai.CSharp.Handlers.IMiraiMessageHandler”转换为“Mirai.CSharp.HttpApi.Handlers.IMiraiHttpMessageHandler”	KMSakuraLib`

由于需要添加handler 所以将所有handler创建好实例后 通过`public override IMessageFrameworkBuilder<TInvokerService, TClientService, THandlerService> AddHandler(THandlerService handlerInstance)`将创建好的实例添加进handlers内 目前不清楚是什么原因导致的 看看作者能不能提供一些解决的方向

**Comment by Executor-Cheng** [comment]
`IMiraiMessageHandler` → `IMiraiHttpMessageHandler`

**Comment by dellbeat** [comment]
> `IMiraiMessageHandler` → `IMiraiHttpMessageHandler`

我先试试 要改很多handler 之前尝试改过没成功

**Comment by Executor-Cheng** [comment]
原来如此, 你用的是实现无关的基层消息框架, 这样的话我再看一看

**Comment by dellbeat** [comment]
> 原来如此, 你用的是实现无关的基层消息框架, 这样的话我再看一看

如果改起来麻烦我这边可以先改成只面向HTTP的

**Comment by Executor-Cheng** [comment]
```csharp
var baseBuilder = servicesCol.AddMiraiBaseFramework();
foreach (IMiraiMessageHandler typeInstance in handlers)//将所有handler通过Bulider接入framework
{
    baseBuilder.AddHandler(typeInstance);
}
var httpBuilder = new MiraiHttpFrameworkCustomBuilder(servicesCol);
httpBuilder.AddDefaultServices();
```

这样子就行
注册基于实现无关的消息框架服务就使用 `MiraiBaseFrameworkBuilder`
注册特定于MAH的服务就使用 `MiraiHttpFrameworkBuilder`

**Comment by dellbeat** [comment]
OK 先试试

**Comment by dellbeat** [comment]
> ```cs
> var baseBuilder = servicesCol.AddMiraiBaseFramework();
> foreach (IMiraiMessageHandler typeInstance in handlers)//将所有handler通过Bulider接入framework
> {
>     baseBuilder.AddHandler(typeInstance);
> }
> var httpBuilder = new MiraiHttpFrameworkCustomBuilder(servicesCol);
> httpBuilder.AddDefaultServices();
> ```
> 
> 这样子就行 注册基于实现无关的消息框架服务就使用 `MiraiBaseFrameworkBuilder` 注册特定于MAH的服务就使用 `MiraiHttpFrameworkBuilder`


可以了 我看了下 我这边没注意到有俩builder 现在试了一下也可以自定义tostring消息了 感谢~
