### ISSUE TITLE
分支release/2.1.0疑似有BUG

### ISSUE THREAD

**Issue by dellbeat** [Executor-Cheng/Mirai-CSharp#99]
向群发送消息时，会抛出异常 导致群消息到达事件无法被触发

`System.InvalidOperationException:“The converter specified on 'Mirai.CSharp.HttpApi.Models.GroupMemberInfo.JoinTime' is not compatible with the type 'System.Nullable`1[System.DateTime]'.”`

附上异常堆栈

```
此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    Mirai.CSharp.HttpApi.Utility.JsonConverters.ChangeTypeJsonConverter<TSrc, TDst>.Read(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions) - 位于 ChangeTypeJsonConverter.cs
    [外部代码]
    Mirai.CSharp.HttpApi.Utility.Utils.Deserialize<T>(System.Text.Json.JsonElement, System.Text.Json.JsonSerializerOptions) - 位于 Utils.cs
    Mirai.CSharp.HttpApi.Parsers.DefaultMappableMiraiHttpMessageParser<TMessage, TImpl>.Parse(System.Text.Json.JsonElement) - 位于 DefaultMappableMiraiHttpMessageParser.cs
    Mirai.CSharp.Framework.Parsers.MessageParser<TRawdata, TMessage>.Mirai.CSharp.Framework.Parsers.IMessageParser<TRawdata>.Parse(TRawdata) - 位于 IMessageParser.cs
    Mirai.CSharp.Framework.Invoking.MessageHandlerInvoker<TClientService, TRawdata>.HandleRawdataAsync(TClientService, TRawdata) - 位于 MessageHandlerInvoker.cs
    [外部代码]
    Mirai.CSharp.HttpApi.Session.MiraiHttpSession.ReceiveMessageLoop(System.Net.WebSockets.WebSocket, Mirai.CSharp.HttpApi.Session.MiraiHttpSession.InternalSessionInfo, System.Threading.CancellationToken) - 位于 MiraiHttpSession.ReceiveMessage.cs
```

测试了一下2.0.0分支不会出现这个问题

**Comment by Executor-Cheng** [comment]
我大意了, 半小时后再处理

**Comment by dellbeat** [comment]
> 我大意了, 半小时后再处理

不着急 先吃顿饭23333

**Comment by dellbeat** [comment]
看了下提交似乎是新增了nullable的datetime和timespan 然后没有设置对应的converter引起的
尝试做了个改动 目前可以正常获取到相关属性
作者可以参考一下(https://github.com/dellbeat/Mirai-CSharp/commit/44d65175e2b73e7302f8cdcd72912e9f712f8adb)

**Comment by Executor-Cheng** [comment]
想了解一下你的Runtime是啥版本的？
我用6.0好像没有问题

**Comment by dellbeat** [comment]
> 想了解一下你的Runtime是啥版本的？ 我用6.0好像没有问题

runtime指 core还是其他的
core的话是[2.9.0-M1](https://github.com/mamoe/mirai/releases/tag/v2.9.0-M1)
因为里面做了一些fix 所以先拿来使用一下

**Comment by Executor-Cheng** [comment]
指的是你.NET的Runtime版本，是Framework还是.NET 3/5/6

**Comment by dellbeat** [comment]
> 指的是你.NET的Runtime版本，是Framework还是.NET 3/5/6

.NET Core 3.1

**Comment by Executor-Cheng** [comment]
原来如此, 3.1和3.0的STJ没有解决 `JsonConverter<T>` 对 `Nullable<T>` 的兼容问题
我会做个wrapper来处理这种情况, 参考 [NullableConverter<T>](https://source.dot.net/#System.Text.Json/System/Text/Json/Serialization/Converters/Value/NullableConverter.cs)

**Comment by dellbeat** [comment]
> 原来如此, 3.1和3.0的STJ没有解决 `JsonConverter<T>` 对 `Nullable<T>` 的兼容问题 我会做个wrapper来处理这种情况, 参考 [NullableConverter](https://source.dot.net/#System.Text.Json/System/Text/Json/Serialization/Converters/Value/NullableConverter.cs)

好的 那等修复了我再应用你这里的更改 我自己的先作为缓解措施使用了

**Comment by Executor-Cheng** [comment]
#100 + Executor-Cheng/Mirai-CSharp@f32eb4fa
